### ISSUE TITLE
Internal error when using Joint attach

### ISSUE THREAD

**Issue by Luke256** [belbs/Py3ODE#7]
When I doing tutorial 2 with pyode, I got the following error
`ODE INTERNAL ERROR 1: assertion "nj < ~((atomicord32)0) / dJCB__MAX" failed in dxStepIsland_Stage1()[step.cpp:951]`
And I found the problem is here:
`j1.attach(body1, ode.environment)`
If I try to comment out here (along with `j2.attach(body1, body2)` below that), no error occurs but the joint doesn't work.
What's the cause of that error?

P.S.
I'm using a processor aarch64. Is it cause of that?

**Comment by filipeabperes** [comment]
Sorry, but I ported this for personal use, and thus (1) I can't make any guarantees on behavior and (2) I don't have the knowledge or time to maintain this properly. 

In the case you mentioned, I'm sorry but I don't know what is causing your error. If you do find out, let me know, though. You might get some luck asking the people responsible for the original PyODE (since the code is basically the same),  or even just using it directly.
